[package]
name = "dylos-agent"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
nix.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["time"] }
tokio-vsock.workspace = true
tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["fmt"] }

[dev-dependencies]
tokio = { workspace = true, features = ["sync", "time", "test-util"] }
