[package]
name = "dylos-store"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
test-hooks = []

[lints]
workspace = true

[dependencies]
dylos-core = { path = "../dylos-core" }
libc = { workspace = true }
nix = { workspace = true, features = ["fs", "dir"] }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
dylos-store = { path = ".", features = ["test-hooks"] }
tempfile = { workspace = true }
