#!/bin/sh
set -e

CMDLINE_FILE="${1:-/proc/cmdline}"
if [ ! -f "$CMDLINE_FILE" ]; then
    echo "net-setup: error: $CMDLINE_FILE not found" >&2
    exit 1
fi

CMDLINE=$(cat "$CMDLINE_FILE")

# Disable DAD, RA, autoconf globally and for default before interfaces are brought up
# (DAD would otherwise start on link up)
sysctl -qw net.ipv6.conf.all.accept_dad=0
sysctl -qw net.ipv6.conf.default.accept_dad=0
sysctl -qw net.ipv6.conf.all.accept_ra=0
sysctl -qw net.ipv6.conf.default.accept_ra=0
sysctl -qw net.ipv6.conf.all.autoconf=0
sysctl -qw net.ipv6.conf.default.autoconf=0

FWD=0

for arg in $CMDLINE; do
    case "$arg" in
        dylos.if=*)
            val="${arg#dylos.if=}"
            IF_NAME="${val%%,*}"
            rest1="${val#*,}"
            MAC="${rest1%%,*}"
            rest2="${rest1#*,}"
            IPV6="${rest2%%,*}"
            
            if [ "$val" = "$rest1" ] || [ "$rest1" = "$rest2" ] || [ -z "$IF_NAME" ] || [ -z "$MAC" ] || [ -z "$IPV6" ]; then
                echo "net-setup: error: malformed dylos.if parameter: $arg" >&2
                exit 1
            fi
            
            IPV4=""
            if [ "$rest2" != "$IPV6" ]; then
                IPV4="${rest2#*,}"
            fi

            ACTUAL_IF=""
            for dir in /sys/class/net/*; do
                if [ -f "$dir/address" ]; then
                    addr=$(cat "$dir/address")
                    if [ "$addr" = "$MAC" ]; then
                        ACTUAL_IF="${dir##*/}"
                        break
                    fi
                fi
            done
            
            if [ -z "$ACTUAL_IF" ]; then
                echo "net-setup: error: no interface found with MAC $MAC" >&2
                exit 1
            fi
            
            if [ "$ACTUAL_IF" != "$IF_NAME" ]; then
                ip link set dev "$ACTUAL_IF" name "$IF_NAME"
            fi
            
            sysctl -qw "net.ipv6.conf.$IF_NAME.accept_dad=0"
            sysctl -qw "net.ipv6.conf.$IF_NAME.accept_ra=0"
            sysctl -qw "net.ipv6.conf.$IF_NAME.autoconf=0"
            
            ip -6 addr add "$IPV6" nodad dev "$IF_NAME"
            if [ -n "$IPV4" ]; then
                ip -4 addr add "$IPV4" dev "$IF_NAME"
            fi
            ip link set dev "$IF_NAME" up
            ;;
        dylos.rt=*)
            val="${arg#dylos.rt=}"
            DST="${val%%,*}"
            GW="${val#*,}"
            case "$DST" in
                *:*)
                    ip -6 route add "$DST" via "$GW"
                    ;;
                *)
                    ip -4 route add "$DST" via "$GW"
                    ;;
            esac
            ;;
        dylos.fwd=1)
            FWD=1
            ;;
        dylos.*)
            echo "net-setup: error: unknown parameter $arg" >&2
            exit 1
            ;;
    esac
done

if [ "$FWD" = "1" ]; then
    sysctl -qw net.ipv6.conf.all.forwarding=1
    sysctl -qw net.ipv4.ip_forward=1
else
    sysctl -qw net.ipv6.conf.all.forwarding=0
    sysctl -qw net.ipv4.ip_forward=0
fi
