[package]
name = "dylos-runtime"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
test-hooks = []

[lints]
workspace = true

[dependencies]
dylos-core = { path = "../dylos-core" }
dylos-fc = { path = "../dylos-fc" }
dylos-net = { path = "../dylos-net" }
dylos-store = { path = "../dylos-store" }
futures-util = { workspace = true, features = ["std", "async-await"] }
nix = { workspace = true, features = ["fs", "signal", "user"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["fs", "process", "sync", "time"] }
tracing = { workspace = true }

[dev-dependencies]
dylos-runtime = { path = ".", features = ["test-hooks"] }
tempfile = { workspace = true }
tokio = { workspace = true, features = ["signal"] }
tracing-subscriber = { workspace = true }
