name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.99.0
          components: rustfmt, clippy

      - uses: taiki-e/install-action@v2
        with:
          tool: just,cargo-nextest,cargo-deny

      - name: Run checks
        run: just check
